server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://122.51.185.50:3306/dahdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: dahdb
    password: tZXDwfhd4mY24CGY